"""Friendly public query API."""

from congreso_open_data.api.congress import Congress, InterventionService
from congreso_open_data.api.errors import (
    AmbiguousEntityError,
    CongressError,
    EntityNotFoundError,
    IncompleteResultError,
    OptionalDependencyError,
    QueryValidationError,
    ResultConsumedError,
    SourceContractError,
    SourceUnavailableError,
)
from congreso_open_data.api.queries import (
    AnyCongressQuery,
    CongressQuery,
    DeputyQuery,
    DocumentQuery,
    FinancialDocumentQuery,
    InitiativeQuery,
    InterestQuery,
    InterventionQuery,
    OrganQuery,
    ProfileQuery,
    RefreshPolicy,
    SalaryEntitlementQuery,
    SortOrder,
    TextPolicy,
    VoteQuery,
    legislature_number,
    legislature_roman,
)
from congreso_open_data.api.records import InterventionRecord
from congreso_open_data.api.results import QueryRun, SearchResult

__all__ = [
    "AmbiguousEntityError",
    "AnyCongressQuery",
    "Congress",
    "CongressError",
    "CongressQuery",
    "DeputyQuery",
    "DocumentQuery",
    "EntityNotFoundError",
    "FinancialDocumentQuery",
    "IncompleteResultError",
    "InitiativeQuery",
    "InterestQuery",
    "InterventionQuery",
    "InterventionRecord",
    "InterventionService",
    "OptionalDependencyError",
    "OrganQuery",
    "ProfileQuery",
    "QueryRun",
    "QueryValidationError",
    "RefreshPolicy",
    "ResultConsumedError",
    "SalaryEntitlementQuery",
    "SearchResult",
    "SortOrder",
    "SourceContractError",
    "SourceUnavailableError",
    "TextPolicy",
    "VoteQuery",
    "legislature_number",
    "legislature_roman",
]
