"""Public API for official Spanish Congress extraction and normalization."""

from congreso_open_data.client import CongressClient
from congreso_open_data.models import (
    ArtifactManifest,
    Deputy,
    DeputyProfile,
    DocumentAsset,
    DocumentText,
    ExtractionCandidate,
    ExtractionEvidence,
    ExtractionFailure,
    ExtractionPlan,
    ExtractionRun,
    ExtractionSpec,
    FinancialDocument,
    Initiative,
    InterestDeclaration,
    Intervention,
    InterventionOccurrence,
    NominalVote,
    Organ,
    OrganMembership,
    SalaryEntitlement,
    SourceRef,
    SpeechBlock,
    VoteEvent,
    VoteItem,
)

__all__ = [
    "ArtifactManifest",
    "CongressClient",
    "Deputy",
    "DeputyProfile",
    "DocumentAsset",
    "DocumentText",
    "ExtractionCandidate",
    "ExtractionEvidence",
    "ExtractionFailure",
    "ExtractionPlan",
    "ExtractionRun",
    "ExtractionSpec",
    "FinancialDocument",
    "Initiative",
    "InterestDeclaration",
    "Intervention",
    "InterventionOccurrence",
    "NominalVote",
    "Organ",
    "OrganMembership",
    "SalaryEntitlement",
    "SourceRef",
    "SpeechBlock",
    "VoteEvent",
    "VoteItem",
]

__version__ = "1.0.0"
